import type { Metadata } from "next"
import "./globals.css"
import Sidebar from "@/components/Partials/Sidebar"
import { urbanist } from "./fonts"
import { Header } from "@/components/Partials/Header"

export const metadata: Metadata = {
    title: "Zufar Syabana",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={urbanist.className}>
                {/* <GradientBackground /> */}
                <Header />
                <Sidebar />
                <main className="min-h-screen relative py-24 lg:py-20 z-10 px-5 lg:pr-10 lg:pl-96">
                    {children}
                </main>
            </body>
        </html>
    )
}
