import type { Metadata } from "next"
import "./globals.css"
import Sidebar from "@/components/Partials/Sidebar"
import GradientBackground from "@/components/Other/GradientBackground"
import { urbanist } from "./fonts"

export const metadata: Metadata = {
    title: "Zufar | Portfolio",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={urbanist.className}>
                {/* <GradientBackground /> */}
                <Sidebar />
                <main className="min-h-screen relative py-20 lg:pr-10 lg:pl-96">
                    {children}
                </main>
            </body>
        </html>
    )
}
